#!/bin/sh
echo "Running build and analyzer checks..."
dotnet build "PolyCartaApi.sln" --no-incremental -warnaserror /clp:NoSummary -v quiet
if [ $? -ne 0 ]; then
    echo "Commit blocked: build failed or analyzer rules violated."
    exit 1
fi
